/**
  * @author NIM/Nama: 13515144 / William
  * Nama file : Sex.java
  */

package src.animal;

public enum Species {
  NONE, ELEPHANT, GIRAFFE, LION, TIGER, ORANGUTAN, CHIMPANZEE, KOMODO, BEAR,
  WHALE, DOLPHIN, CLOWNFISH, BLUETANG, PIRANHA, PUFFFISH, EAGLE, CENDRAWASIH,
  OWL, BAT, MACAU, COCKATOO, FROG, ALLIGATOR, HIPPOPOTAMUS, TURTLE
}
